name: CI(RSpec)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - docs/**
      - Dockerfile
      - docker-compose.*

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - echo Setup
  rspec-on-ruby-3.0:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - run: make ci-ruby-3.0
  rspec-on-ruby-2.7:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - run: make ci-ruby-2.7
  rspec-on-ruby-2.6:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - run: make ci-ruby-2.6
  all-ok:
    runs-on: ubuntu-latest
    needs: [rspec-on-ruby-3.0, rspec-on-ruby-2.7, rspec-on-ruby-2.6]
    sptes:
      - run: echo all ok
